apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "simplequarkus"
  description: "Simple app"
  tags:
    - java
    - quarkus
  links:
    - url: https://che-eclipse-che.apps.cluster-sxjwp.sxjwp.sandbox1298.opentlc.com/#https://github.com/sabre1041-backstage-demo/simplequarkus?devfilePath=.devfilev2-theia.yaml
      title: CodeReady Workspaces (Eclipse Theia)
      icon: web
    - url: https://che-eclipse-che.apps.cluster-sxjwp.sxjwp.sandbox1298.opentlc.com/#https://github.com/sabre1041-backstage-demo/simplequarkus?che-editor=che-incubator/che-code/insiders&devfilePath=.devfilev2-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web    
    - url: https://che-eclipse-che.apps.cluster-sxjwp.sxjwp.sandbox1298.opentlc.com/#https://github.com/sabre1041-backstage-demo/simplequarkus?che-editor=che-incubator/che-idea/next&devfilePath=.devfilev2-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
    - url: https://grafana-route-user-workload-grafana.apps.cluster-sxjwp.sxjwp.sandbox1298.opentlc.com/d/AqEG4weWk/error-budget?orgId=1&refresh=5s&var-virtual_service=simplequarkus.simpleapp-prod.svc.cluster.local&var-time_interval=1h&var-SLO=95&var-latency=1000
      title: SRE Metrics (production)
      icon: web
  annotations:
    github.com/project-slug: sabre1041-backstage-demo/simplequarkus
    'backstage.io/kubernetes-id': simplequarkus
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=simplequarkus'
    'backstage.io/techdocs-ref': dir:.
    'sonarqube.org/project-key': sabre1041-backstage-demo_simplequarkus
    'prometheus.io/alert': ErrorBudgetBurn-critical-simpleapp-prod-simplequarkus,ErrorBudgetBurn-warning-simpleapp-prod-simplequarkus
    'prometheus.io/rule': virtual_service:simpleapp_prod_simplequarkus:error_rate_1d,virtual_service:simpleapp_prod_simplequarkus:error_rate_1h,virtual_service:simpleapp_prod_simplequarkus:error_rate_2h,virtual_service:simpleapp_prod_simplequarkus:error_rate_30m
spec:
  type: service
  lifecycle: experimental
  owner: "team1"
  system: system:simpleapp